// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xdOCiZ9HYp-Cose1m5YMPq_kGt0fMkU',
    appId: '1:160631853733:android:94725d43b1f0edf285734c',
    messagingSenderId: '160631853733',
    projectId: 'ludo-4984e',
    databaseURL: 'https://ludo-4984e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ludo-4984e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2goOQ8Za6Jui773gHqprj9xz3FIJNUqA',
    appId: '1:160631853733:ios:c48d30784504b84185734c',
    messagingSenderId: '160631853733',
    projectId: 'ludo-4984e',
    databaseURL: 'https://ludo-4984e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ludo-4984e.firebasestorage.app',
    iosBundleId: 'site.smstudios.ludoApp',
  );
}
